[package]
name = "spaceship_game"
version = "0.1.1"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.15" }
rand = "0.8.5"

[dev-dependencies]
bevy_dylib = "0.15"
